### PR TITLE
Custom export filenames

### PR DESCRIPTION
**Pull request by OptimusRhine**
* modified options to use custom filenames for Staff, Admin, and Patient list exports
  * custom filename is `<table_object>List_<datetimestamp` (e.g. `StaffList_08092017150707.csv`)

### CODE REVIEW

**Comment by OptimusRhine** [comment]
@achen2401 Would you mind taking a look at this, when you get a chance? My `exportOptions` changes worked perfectly for the Admin and Staff tables, but for some reason the same code isn't working for the Patient table (it's just using the default name)...

**Comment by achen2401** [comment]
@OptimusRhine 
Adam, I figured out why the export file naming wasn't working for patients list - moving the initiation of table outside of document ready block seems to resolve it - I am still not sure why it wasn't working if it was in that block yet.. also I hope it is okay that I moved the code for naming the export file name to one function call?  Let me know if you find any issue with my changes?

**Comment by OptimusRhine** [comment]
@achen2401 Looks good to me, and also works for me all on the tables now - thanks! My only question would be, was it intentional to use two underscores in the filename, instead of one (e.g. `StaffList__` instead of `StaffList_`)? I think one might look cleaner, but I'm fine with two if that was an intentional change.

**Comment by achen2401** [comment]
@OptimusRhine 
Adam, I think I really meant to just use one underscore there, sorry for the confusion! I agree, one underscore is cleaner.

**Comment by OptimusRhine** [comment]
@achen2401 Ah ok cool, updated it to just use one then. Thanks for your help here!

**Pull request merged**
