### PR TITLE
Show error msg, and don't load next page, on failed contact request

### PR DESCRIPTION
**Pull request by OptimusRhine**
https://www.pivotaltracker.com/story/show/148387559

* modified `/contact` [POST] API endpoint logic:
  * abort 400 on unverified recaptcha during POST (instead of previous page reload)
  * on success, just return json containing the `msgid: <email.id>`
* modified contact.html page (both gil and non-gil)
  * changed 'Submit' button press logic from submission + page load, to an ajax call
    * on button press, hide button (to prevent multiple resubmissions) and show loading message
    * on failed response, display error message and re-show button
    * on successful response, load contact_sent.html page (using returned `msgid` as url param)

### CODE REVIEW

**Comment by OptimusRhine** [comment]
@achen2401 Would you mind taking a look, and improving wherever you see fit?

The two most obvious places for changes that I can see (but don't really know how to implement the improvements):
- Replace 'Sending contact request...' with the cycling loading graphic that we use in other places (like when modifying a patient profile)
- Better formatting (maybe red text, centered above submit button, etc) for displayed response error messages

Thanks!

**Comment by achen2401** [comment]
@OptimusRhine 
Adam, I will checkout your branch and have a look.  Thank you for making the changes!

**Comment by achen2401** [comment]
@OptimusRhine Adam, I addressed the things you mentioned:

Replace 'Sending contact request...' with the cycling loading graphic
Add formatting for displayed response error messages

Do you mind taking another look just to make sure I didn't break anything?

Thank you again for making the changes.

**Comment by OptimusRhine** [comment]
@achen2401 Awesome! I tested this out on both the GIL and non-GIL contact pages, and it's working great (and looks much better with your changes). Thanks for helping me out!

**Pull request merged**
