### PR TITLE
Revert "Revert "front-end changes to convert consent date based on patient timezone""

### PR DESCRIPTION
**Pull request by ivan-c**
Revert of revert, Amy's changes
uwcirg/true_nth_usa_portal/pull/1182

### CODE REVIEW

**Comment by pbugni** [comment]
Beyond the conflict needing a rebase - is this ready to again be merged?

**Comment by achen2401** [comment]
Hi, Paul, I meant to follow up with Ivan.  @ivan-c Ivan, not sure if you have reviewed this. I'd love to have these changes merged as they address one of the stories that was assigned to me (https://www.pivotaltracker.com/story/show/149409969) for Eproms August release.  I have rebased this branch. I didn't make the fix suggested by PEP8.  I wasn't sure if that would break anything.

**Comment by achen2401** [comment]
Holding off on merging this change, not sure if Mo still wants it

**Comment by achen2401** [comment]
closing this now,  will re-open when Mo has firmed the requirements for htis.

**Pull request closed without merging**
