### PR TITLE
Add ePROMs languages

### PR DESCRIPTION
**Pull request by ivan-c**
Add ePROMs language codings

### CODE REVIEW

**Comment by ivan-c** [comment]
@pbugni These aren't appearing in my `codings` table after deploying, am I missing some association (to orgs)?

**Comment by pbugni** [comment]
@ivan-c codings are very generic - those *should* now be visible in the eproms db's coding table (post seed | sync), but that in itself doesn't associate them with an org.

@OptimusRhine can correct me if I'm wrong (he did the locale work) but I believe each organization can have 2 related entries in its site persistence - one for `default_locale` and a list under extensions to make each available as an option for the org's clients, i.e.

```
      "extension": [
        {
          "url": "http://hl7.org/fhir/valueset/languages",
          "valueCodeableConcept": {
            "coding": [
              {
                "code": "en_AU",
                "display": "Australian English",
                "system": "urn:ietf:bcp:47"
              }
            ]
          }
        }
]
```

**Comment by ivan-c** [comment]
Don't merge, needs some further UI work to surface `locale_display_options()` in UI

**Comment by ivan-c** [comment]
@pbugni Any idea why the tests aren't passing? 
Those new orgs seem OK, could it be a race condition loading the `Codings.json`?

**Comment by ivan-c** [comment]
Looks good, merging. Thanks @pbugni !

**Pull request merged**
